include:
  - project: graphaware/devops/gitlab-ci-templates
    file: gitlab-ci-templates.yml

stages:
  - test # TBD later, instead of travis
  - deploy
  - postDeploy
  - triggers

bumpVersion:
  extends: .frameworkVersionBump
  stage: deploy
  script:
    - NEW_VERSION="${VERSION%.*}.$((${VERSION##*.}+1))-SNAPSHOT"
    - CUSTOM_SPACE='    ' #otherwise bash joins spaces into one
    - CHANGELOG_MSG="${CHANGELOG_MSG:-${VERSION}:\n${CUSTOM_SPACE}- Upgrade to Neo4j ${VERSION%.*}}\n"
    - echo -e "$CHANGELOG_MSG\n$(cat changes.txt)" > changes.txt # add the message into changes.txt, -e enable special characters (\n)
    - git commit -a -m "Release with new neo4j version"  #You can add edition of a file to pom using ant-plugin. You can connect it to the goals of the maven release plugin. But this plugin won't commit anything else but POMs!!!
    - echo "Special ssh key only for testing, don't worry!"
    - echo $REPO_SSH
    - echo $REPO_ADR
    - git push origin $CI_COMMIT_REF_NAME
  only:
    refs:
      - master
      - CItesting
    variables:
      - $VERSION

uploadArtifact:
  extends: .uploadToS3
  stage: postDeploy
  dependencies:
    - bumpVersion
  variables:
    FROM: target/checkout/build/graphaware-framework-server/target/graphaware-server-all-$VERSION.jar
    TO: $AWS_PATH/graphaware-server-all-$VERSION.jar
  only:
    refs:
      - master
    variables:
      - $VERSION

#Delay triggers by 30 minutes - maven central needs some time to process the artifacts
delay30mins:
  stage: postDeploy
  when: delayed
  start_in: 30 minutes
  script:
    - echo "Delaying"
  only:
    refs:
      - master
    variables:
      - $VERSION

#trigger template
.trigger:
  stage: triggers
  variables:
    PARENT_VERSION: $VERSION
  only:
    refs:
      - master
    variables:
      - $VERSION

triggerUUID:
  extends: .trigger
  trigger: GraphAware/neo4j-plugins/neo4j-uuid

triggerRestTest:
  extends: .trigger
  trigger: GraphAware/neo4j-plugins/neo4j-resttest

triggerExpire:
  extends: .trigger
  trigger: GraphAware/neo4j-plugins/neo4j-expire

triggerRecommendation:
  extends: .trigger
  trigger: GraphAware/neo4j-plugins/neo4j-reco

triggerTriggers:
  extends: .trigger
  trigger: GraphAware/neo4j-plugins/neo4j-triggers

triggerTimetree:
  extends: .trigger
  trigger: GraphAware/neo4j-plugins/neo4j-timetree

triggerGAstarter:
  extends: .trigger
  trigger: GraphAware/neo4j-plugins/graphaware-starter

triggerRecommendationsMeetup:
  extends: .trigger
  trigger: GraphAware/neo4j-plugins/recommendations-meetup

#neo4j-to-elasticsearch is launched from UUID as it depends on it
